packages:
  - apps/*
  - packages/*
allowBuilds:
  bcrypt: true
  cpu-features: false
  protobufjs: false
  ssh2: false
injectWorkspacePackages: true
minimumReleaseAgeExclude:
  - "@types/node@24.13.4"
minimumReleaseAgeStrict: true
