import fs from 'node:fs';
const commits={A:'f1194d4dfd069982752a12f812e82a188f7dd898',B:'3d11c5ff7333dee51b1b764f9e67f407b818684a'};
// Curated records; generated formatting does not generate architectural conclusions.
const records=[
['E01','A','src/index.ts','34-273','bootstrap','Bun process','app.listen; registerJobHandler; start workers; stop workers','API, websocket publisher e workers são compostos no processo; signals param timers e encerram processo.','Não é comprovado drain integral de chamadas externas em voo.','Quem garante término dos writes antes de process.exit?'],
['E02','A','src/modules/agents/service.ts','1184-1356','createAgent','agents.controller POST /v1/agents; MCP authoring','parseInput; assertAgentCreatable; runScopedOn; tx.agent.create; audit','Agente é criado como registro tenant-scoped; defaults do serviço enabled=true e mode=test; modelo não instanciado nesse passo.','Configuração persistida é distinta da instância de modelo/grafo por turno.','Não há snapshot imutável de AgentVersion no schema.'],
['E03','A','src/modules/chatwoot/webhook.ts','1234-1338','receiveChatwootWebhook; recordAndProcessChatwootDelivery','src/api/v1/chatwoot.controller.ts:23-72','resolveRouteToken; verifySignature; claimDelivery; processChatwootDelivery','Receiver verifica token/HMAC, parseia e normaliza; controller inicia registro/processamento sem await antes de ACK.','[INFERENCE] Existe janela de crash entre ACK e claim persistido, apesar de recuperação dos registros já existentes.','Crash nessa janela não foi injetado; cache/refresh de rota podem consultar banco.'],
['E04','A','src/graph/runtime.ts','2285-2498','runAgentTurn','processChatwootDelivery','loadAgentConfig; runLoadedTurn; advanceHandledWatermark','Mensagem renderizável e binding elegível são necessários; checks de mensagem mais nova e watermark influenciam entrega.','Responder não equivale a simplesmente invocar o modelo.','Races cross-process não validadas com DB neste ambiente.'],
['E05','A','src/graph/runtime.ts','579-1022','runLoadedTurn; runTurnBody','runAgentTurn; debounce handler','buildToolset; buildModelAndGraph; buildCallbacks; status reporter','Turno constrói estado mutável de anexos/handoff, closures de fencing, ferramentas e grafo.','Não é instância de uma classe Agent autônoma persistente.','Cobertura dos outros entrypoints é seletiva.'],
['E06','A','src/graph/runtime.ts','1258-1798','graph invocation path','runTurnBody','drain ingest; markTurnOwning; graph.getState; graph.updateState; graph.invoke','Histórico existente/attendance boundaries e guardrails precedem invoke com HumanMessage e thread_id.','Checkpoint e entrada atual são combinados pelo grafo; transação SQL não permanece aberta no LLM.','Sem provider real e sem DB, caminho completo não foi executado aqui.'],
['E07','A','src/graph/runtime.ts','1792-2266','delivery and cleanup','graph.invoke result','deliverText; guardrails; attachment delivery; clear turn ownership','Saída pode ser suprimida, entregue parcialmente ou transferida; finally limpa in-flight e ownership.','Efeito externo e checkpoint não são uma transação única.','Exatamente uma entrega externa não é garantia demonstrada.'],
['E08','A','src/graph/prepare.ts','335-832','loadAgentConfig','runtime; playground; memory','agent.findFirst; vault resolution; loadToolSelections; composeSystemPrompt; interpolatePrompt','Prompt efetivo escolhe override, variante ou Agent.systemPrompt; acrescenta grounding, variáveis e contexto de atributos/agendamento.','Descrição de Agent no banco é configuração; LoadedAgentConfig contém credenciais resolvidas por execução.','Conteúdo final varia por tenant/conversa/tempo; não há prompt universal.'],
['E09','A','src/graph/graph.ts','441-711','agentNode; toolsNode; StateGraph','buildModelAndGraph','selectHistoryWindow; bindTools; runModelCall; ToolNode.invoke; toolsCondition','Grafo agent↔tools itera; normaliza SystemMessage; limite por resultados após último Human; tools boundary pode recusar lote.','Limite não é scheduler nem workflow de negócio; paralelismo do lote pode ultrapassar teto antes do próximo check.','[INFERENCE] Overshoot não foi medido com side effects reais.'],
['E10','A','src/graph/prompt.ts','23-304','composeSystemPrompt; buildPromptVars; interpolatePrompt','loadAgentConfig','sanitizePromptValue; time/calendar formatting','Prompt base é concatenado com grounding condicional; variáveis conhecidas interpoladas; desconhecidas permanecem.','Texto de skill não é automaticamente inserido neste pipeline.','Dados externos ainda podem conter conteúdo adversarial.'],
['E11','A','src/graph/prepare.ts','943-1325','buildToolset','runTurnBody; playground','loadMcpTools; native/document/HTTP/code/toolpack/RAG builders; dropDuplicateToolNames; applyToolPreconditions','Ferramentas convergem em lista única, nome único e wrappers de precondição depois do merge.','Grants e unicidade são fronteiras relevantes; nomes ainda são coupling de prompts/precondições.','Colisões removidas com warning podem alterar capacidade esperada.'],
['E12','A','src/graph/tools/assemble.ts','153-460','loadToolSelections','loadAgentConfig','agentToolSelection.findMany; relation mapping','Selections persistidas distinguem NATIVE/HTTP/MCP/RAG/INTEGRATION/DOCUMENT/CODE.','Não são Skill records; são grants/conexões/definições.','Versões das dependências não são congeladas por run.'],
['E13','A','src/graph/tools/native.ts','1370-1392','buildNativeTools','buildToolset','13 native builders; filter by Set','Ausência de seleção NATIVE permite conjunto padrão; enabledTools=[] explicitamente permite nenhum nativo.','Contradiz instrução operacional de B que equipara allowlist vazia a todas.','Legacy migrations/config podem afetar grants históricos, não esse filtro.'],
['E14','A','src/graph/tools/http.ts','522-931','buildHttpTool','buildHttpTools; ToolNode','schema parser; credential resolver; template interpolation; assertSafeOutboundUrl; fetchBounded; toolFailure','Argumentos estruturados viram request com contexto/secret injection; origem/host e SSRF verificados; resultado é texto limitado.','HTTP status esperado pode ser resultado normal; ferramenta não é proxy HTTP irrestrito sem governança.','DNS check e fetch não demonstram pinning da resolução; TOCTOU não explorado.'],
['E15','A','src/graph/tools/failure.ts','1-54','failableTool; toolFailure','HTTP/CODE/RAG builders','LangChain tool wrapper; ToolMessage','Falha marcada retorna ToolMessage status=error quando há tool_call_id; chamada plain args devolve string.','Erro voltado ao modelo não é necessariamente exceção do turno.','Ver também tratamento de exceções no ToolNode instalado.'],
['E16','A','src/graph/tools/mcp.ts','241-444','buildMcpContextSection; loadMcpTools','buildToolset; buildModelAndGraph','MultiServerMCPClient; getTools; OAuth refresh; namespace filter','MCP tools são conectadas, filtradas por allowlist e namespaced; server instructions entram no system prompt.','[INFERENCE] Instruções remotas nesse nível ampliam risco de injection/poisoning.','Nenhum ataque foi executado; confiança no servidor é requisito externo.'],
['E17','A','src/graph/tools/code-sandbox.ts','24-280','runSandboxedCode','buildCodeTool / invokeCodeTool','Worker; queue; timer; terminate; QuickJS worker','Código salvo executa em Worker+QuickJS com limites de tempo/memória/stack e fila; não é ferramenta nativa run_code.','Sandbox restringe API JS exposta; não equivale a isolamento de processo/VM para todo tipo de ferramenta.','Um teste de orçamento falhou no ambiente; não prova escape.'],
['E18','A','src/modules/agents/service.ts','2273-2389','replaceAgentToolSelections','REST/MCP configuration','transaction locks; normalizeGrants; deleteMany; createMany; audit; broadcast','Substituição de grants é transacional com checagem opcional de updatedAt e validação de referências.','Controle otimista de edição não é versionamento imutável de deployment.','Publicação realtime pode ser best-effort.'],
['E19','A','src/graph/checkpointer.ts','24-95','getCheckpointer; resolveGraphThreadId','buildModelAndGraph','PostgresSaver.setup; pg.Pool; tenant thread prefix','Histórico do grafo persiste em schema langgraph; thread pode usar contactInbox em vez de conversation id.','Memória conversacional pode atravessar atendimentos da mesma relação contato/inbox.','Isolamento de langgraph depende de controles de aplicação; não demonstrada RLS igual às tabelas Prisma.'],
['E20','A','src/modules/memory/compact.ts','176-750','runMemoryCompact','MEMORY_COMPACT handler','summarizeAttendance; attendanceSummary.upsert; graph.updateState; RemoveMessage','Resumo é salvo antes de rewrite; prefixo é revalidado sob fila; até 20 resumos alimentam memory head; mudanças/busy adiam.','Resumo de atendimento é memória persistida derivada, não vector memory generalizada.','Atomicidade entre stores não existe; recovery/reuse mitigam parte da janela.'],
['E21','A','src/modules/scheduler/worker.ts','231-370','runClaimed; runSchedulerTick','startup timers','claimDue; handlers; complete/fail/reschedule; Promise.allSettled','Jobs persistidos executam com claims e concorrência de lotes; handlers despachados por registry local.','Scheduler existe; não há motor genérico de workflow versionado demonstrado.','Escala/fairness entre réplicas requer teste de carga com DB.'],
['E22','A','src/modules/rag/service.ts','35-79','searchKnowledge','search_knowledge tool','resolve embedding credentials; embed; scoped vector SQL','Busca usa KBs autorizadas/modelo compatível e embedding fora da transação SQL.','Conhecimento recuperado é resultado de ferramenta, não toda base injetada automaticamente.','Qualidade de retrieval e vazamento semântico não medidos.'],
['E23','A','src/features/realtime/service.ts','22-200','publisher and broadcast helpers','services; src/index.ts','Bun server.publish; JSON.stringify','Realtime usa conexões/tópicos e publisher local ao processo.','Não foi localizado fanout cross-replica ou cursor durável de replay nesse caminho.','Infraestrutura externa de produção não está acessível.'],
['E24','A','src/modules/webhooks/outbound/service.ts','16-58','emitOutbound','domain callers with scoped tx','webhookSubscription.findMany; outboundWebhookDelivery.createMany','Cria entregas PENDING por assinatura com envelope persistido.','Há mecanismo outbound durável; não prova event sourcing de todos os agregados.','Atomicidade depende de caller usar a mesma transação da mutação.'],
['E25','A','src/modules/flowlog/service.ts','105-212','emitFlowEvent; withFlowStage','runtime/callbacks/tool handlers','writeFlow; runScopedOn; executionLog.create; alert dispatch','Log é write assíncrono rastreado, redigido e com falha capturada; withFlowStage relança erro de operação.','Observabilidade não deve ser confundida com commit durável de AgentStep.','Queda de processo pode perder writes pendentes.'],
['E26','A','src/lib/tenancy/multi-tenant.ts','65-219','runScopedOn; asSuperAdminOn','domain services','Prisma extension; set_config tenant context; transaction','Create injeta tenant e transação configura contexto para RLS; plano fleet tem contexto separado.','Segurança exige papel runtime correto e migrations RLS, não só filtro TypeScript.','Testes DB/RLS não executados aqui; ver scripts/db-bootstrap.sql.'],
['E27','A','src/lib/ssrf.ts','209-291','assertSafeOutboundUrl','HTTP tools and outbound clients','URL parse; DNS lookup all addresses; address validation','Guard verifica URL e IPs resolvidos; opções de desenvolvimento alteram aceitação de privados/HTTP.','Controle de configuração importa; não declarar proteção absoluta contra SSRF.','[INFERENCE] Gap entre lookup e conexão precisa teste dedicado.'],
['E28','A','src/modules/guardrails/analyze.ts','238-315','analyzeText','runtime input/output gate','structured/raw verdict invocation; runModelCall; readVerdict','Falha de análise é registrada e retorna unanalyzed: política efetiva é fail-open nesse ponto.','Guardrail LLM não substitui autorização determinística fail-closed.','Modos/chamadores podem decidir tratamento adicional; não generalizar para todo gate.'],
['E29','A','src/client/App.tsx','1-320','App routing','client entrypoint','BrowserRouter; protected layouts; pages','SPA possui superfícies de agentes, recursos e operação próprias de A.','Essas rotas não são evidência das rotas internas do CRM-Modelo.','Detalhes de cada página não auditados linha a linha.'],
['E30','A','src/graph/models.ts','178-285','createChatModel','buildModelAndGraph; fallback builder','ChatOpenAI; ChatAnthropic; ChatGoogleGenerativeAI; ChatDeepSeek','Factory tem branches por provider, baseURL e adaptações de reasoning/tools Gemini.','BaseChatModel abstrai invoke, mas parâmetros/transportes não são uniformes.','Sem requests autenticados reais; capacidades variam por modelo.'],
['E31','A','src/graph/history-window.ts','49-110','selectHistoryWindow','agentNode','countMessageTokens callback; human-boundary selection','Recorta só input por estimativa e preserva última unidade humana mesmo se ultrapassa budget.','Não é limite estrito do request total e não remove mensagens persistidas.','System prompt e schemas de tools ficam fora desse orçamento.'],
['E32','A','src/graph/model-fallback.ts','28-54','isFallbackWorthy','agentNode/runModelCall handling','providerFailure; statusOf; transient classifier','Timeout/estados transitórios/empty completion podem ativar fallback; indiscriminadamente qualquer erro não.','Quando disponível, primary retries=0 e timeout45s; fallback fica sticky no turno.','Transportes diferem em suporte a timeout; Google não recebe timeout nesse factory.'],
['E33','A','src/graph/thread-claim.ts','59-250','markTurnOwning; leases','runtime; ingest; compaction','durable thread columns; epoch; renewal; holder count','Contador de holders+epoch protege uso do thread contra rewrite; fila local é outra camada.','Não chamar esse lease de mutex exclusivo de todos os turnos.','Garantia distribuída completa requer examinar fences de cada caller e testes DB.'],
['E34','B','skills/agents-onboarding/references/08-agent-import.md','1-90','agent import procedure','SKILL.md route','agent_import; agent_prompt_set via external assistant MCP','Skill instrui um assistente de implantação a importar JSON e configurar prompt do agente.','[DOC] Meta-layer de autoria, não skill executada no atendimento.','Mecanismo de injeção pelo host de coding assistant não consta no repositório.'],
['E35','B','skills/agents-operation/references/03-adjust.md','1-65','native allowlist guidance','agents-operation SKILL.md','operator MCP configuration','Texto equipara allowlist vazia a todas as nativas, divergente do filtro runtime de A.','[DOC] Usar código/tests para [] versus ausência.','Confirmar intenção editorial com mantenedores não feito.'],
['E36','B','skills/agents-onboarding/scripts/remote.py','1-210','SSH execution helper','external coding assistant/operator CLI','argparse; subprocess.run; ssh','Script operacional prepara argumento SSH e envia arquivo/comando; não carrega runtime de cliente.','[CODE] Skill pode ter código auxiliar, além de instruções e recursos.','Não executado porque teria efeitos de administração externos.'],
['E37','A','src/graph/tools/native.ts','288-444','handoff_to_human','ToolNode','private note; toggleStatus; assignConversation; side effect logger','Status pode mudar antes de assignment; assignment failure é registrado e resultado ainda pode indicar handoff.','Efeito parcial exige contrato mais rico no novo produto.','Não demonstrado rollback remoto; tests/tools.test.ts:840–870 corroboram.'],
['E38','A','src/modules/memory/summarize.ts','143-285','summarizeAttendance','runMemoryCompact','transcript filtering; SystemMessage; HumanMessage; model','Resumo separa falas, exclui resultados de tools/markers e limita transcript; erro deixa thread intacto.','Resumos perdem informação por desenho; preservar proveniência é proposta.','Qualidade factual de resumo real não avaliada.'],
];
// Correções verificadas contra a árvore e a numeração efetivas do snapshot.
const correctedRanges={E01:'34-255',E24:'16-52',E27:'209-267',E29:'1-289',E34:'1-66',E35:'1-48',E36:'1-199'};
for(const r of records){
 if(correctedRanges[r[0]])r[3]=correctedRanges[r[0]];
 if(r[0]==='E23')r[2]='src/api/features/realtime/realtime.service.ts';
 if(r[0]==='E34')r[6]='agent_import; prompt_set via external assistant MCP';
}
let md='# Registro de evidências críticas\n\nCada registro é uma descoberta delimitada, não uma certificação de segurança. HIGH = código/call chain inspecionado; não significa deploy validado. Registros documentais B provam instrução de autoria, não execução do consumidor externo. Dependências instaladas têm evidência separada no Volume I.\n\n';
for(const [id,repo,p,lines,symbol,caller,callee,claim,interpretation,questions] of records){
 const r=repo==='A'?'agents':'agents-skills';const url=`https://github.com/fazer-ai/${r}/blob/${commits[repo]}/${p}#L${lines.replace('-','-L')}`;
 md+=`<a id="${id.toLowerCase()}"></a>\n## ${id}\n\nID: ${id}  \nClaim: ${claim}  \nStatus: ${p.endsWith('.md')?'[DOC]':'[CODE]'} observado no snapshot  \nConfidence: HIGH para o comportamento delimitado; inferências/unknowns não herdam prova de execução  \nRepository: ${repo} — ${r}@${commits[repo]}  \nPath: [${p}](${url})  \nSymbol: \`${symbol}\`  \nLines: ${lines}  \nCaller: ${caller}  \nCallee: ${callee}  \nEvidence: implementação referenciada; validação cruzada na seção 25 e no anexo de casos  \nInterpretation: ${interpretation}  \nOpen questions: ${questions}\n\n`;
}
fs.writeFileSync('research/evidence-ledger.md',md);
fs.writeFileSync('research/evidence/critical-records.json',JSON.stringify(records,null,2));
console.log({records:records.length});
