import fs from 'node:fs';
import path from 'node:path';
const root='/tmp/maria-research-agents';
const out=path.resolve('research/evidence');
const args=process.argv.slice(2);
const command=['bun','test',...args];
const env={PATH:process.env.PATH,NODE_ENV:'test',ALLOW_NO_DB:'1',XDG_CACHE_HOME:'/tmp/maria-prisma-cache'};
const p=Bun.spawn(command,{cwd:root,env,stdout:'pipe',stderr:'pipe'});
const [stdout,stderr,exitCode]=await Promise.all([new Response(p.stdout).text(),new Response(p.stderr).text(),p.exited]);
const label=process.env.RESEARCH_TEST_LABEL??(args.length?'focused':'suite');
fs.writeFileSync(path.join(out,`tests-${label}.log`),stdout+'\n'+stderr);
fs.writeFileSync(path.join(out,`tests-${label}.json`),JSON.stringify({command,env,exitCode,runtime:Bun.version,finishedAt:new Date().toISOString(),limitations:['ALLOW_NO_DB=1: database tests may skip','No live LLM/provider credentials supplied']},null,2));
console.log((stdout+'\n'+stderr).slice(-6500));
console.log({exitCode});
